export const books = [
  {
    id: 1,
    title: "The Art of Focus",
    author: "James Carter",
    genre: "Self-Help",
    price: 299,
    rating: 4.4,
    pages: 240,
    language: "English",
    publishedYear: 2022,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794",
    description:
      "A practical guide to improving focus and productivity in a distracted world.",
    stock: 40,
  },
  {
    id: 2,
    title: "JavaScript for Beginners",
    author: "Emily Watson",
    genre: "Technology",
    price: 499,
    rating: 4.6,
    pages: 380,
    language: "English",
    publishedYear: 2023,
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f",
    description:
      "Learn JavaScript from scratch with real-world examples and clear explanations.",
    stock: 25,
  },
  {
    id: 3,
    title: "The Silent Night",
    author: "Robert Miles",
    genre: "Fiction",
    price: 349,
    rating: 4.2,
    pages: 310,
    language: "English",
    publishedYear: 2021,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c",
    description:
      "A suspense-filled fictional story that keeps readers hooked till the end.",
    stock: 60,
  },
  {
    id: 4,
    title: "Think Like a Leader",
    author: "Sophia Brown",
    genre: "Business",
    price: 399,
    rating: 4.5,
    pages: 280,
    language: "English",
    publishedYear: 2020,
    image: "https://images.unsplash.com/photo-1519682337058-a94d519337bc",
    description:
      "Leadership principles and decision-making strategies for modern professionals.",
    stock: 35,
  },
  {
    id: 5,
    title: "Mastering React",
    author: "Daniel Scott",
    genre: "Technology",
    price: 599,
    rating: 4.8,
    pages: 420,
    language: "English",
    publishedYear: 2024,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765",
    description:
      "An advanced guide to building scalable applications using React.",
    stock: 20,
  },
  {
    id: 6,
    title: "The Habit Code",
    author: "Laura Green",
    genre: "Self-Help",
    price: 279,
    rating: 4.3,
    pages: 210,
    language: "English",
    publishedYear: 2019,
    image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d",
    description:
      "Understand how habits are formed and how to change them effectively.",
    stock: 55,
  },
  {
    id: 7,
    title: "Startup Success",
    author: "Michael Turner",
    genre: "Business",
    price: 449,
    rating: 4.6,
    pages: 330,
    language: "English",
    publishedYear: 2022,
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66",
    description:
      "A complete roadmap for launching and growing a successful startup.",
    stock: 30,
  },
  {
    id: 8,
    title: "Mystery of the Lost Island",
    author: "Olivia Harris",
    genre: "Fiction",
    price: 369,
    rating: 4.1,
    pages: 290,
    language: "English",
    publishedYear: 2021,
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353",
    description:
      "An adventurous journey full of mystery, danger, and discovery.",
    stock: 48,
  },
  {
    id: 9,
    title: "Data Structures Simplified",
    author: "Kevin Lee",
    genre: "Technology",
    price: 529,
    rating: 4.7,
    pages: 400,
    language: "English",
    publishedYear: 2023,
    image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93",
    description:
      "A beginner-friendly explanation of data structures with examples.",
    stock: 22,
  },
  {
    id: 10,
    title: "Mindful Living",
    author: "Rachel Adams",
    genre: "Self-Help",
    price: 259,
    rating: 4.0,
    pages: 200,
    language: "English",
    publishedYear: 2018,
    image: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d",
    description:
      "Simple techniques to live a calm, balanced, and meaningful life.",
    stock: 70,
  },
  {
    id: 11,
    title: "The Coding Journey",
    author: "Andrew White",
    genre: "Technology",
    price: 479,
    rating: 4.5,
    pages: 360,
    language: "English",
    publishedYear: 2020,
    image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0ea",
    description: "A roadmap for beginners entering the world of programming.",
    stock: 34,
  },
  {
    id: 12,
    title: "Psychology of Success",
    author: "Natalie King",
    genre: "Business",
    price: 389,
    rating: 4.6,
    pages: 300,
    language: "English",
    publishedYear: 2021,
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66",
    description:
      "Understand the mindset and psychology behind successful people.",
    stock: 28,
  },
  {
    id: 13,
    title: "The Last Promise",
    author: "Ethan Moore",
    genre: "Fiction",
    price: 359,
    rating: 4.2,
    pages: 315,
    language: "English",
    publishedYear: 2022,
    image: "https://images.unsplash.com/photo-1524578271613-d550eacf6090",
    description: "An emotional story of love, loss, and redemption.",
    stock: 52,
  },
  {
    id: 14,
    title: "Full Stack Development",
    author: "Chris Johnson",
    genre: "Technology",
    price: 649,
    rating: 4.8,
    pages: 450,
    language: "English",
    publishedYear: 2024,
    image: "https://images.unsplash.com/photo-1526318472351-bc6c9b36e5a5",
    description:
      "Become a full stack developer with hands-on projects and examples.",
    stock: 18,
  },
  {
    id: 15,
    title: "Smart Money Habits",
    author: "Brian Clark",
    genre: "Finance",
    price: 329,
    rating: 4.4,
    pages: 260,
    language: "English",
    publishedYear: 2019,
    image: "https://images.unsplash.com/photo-1553729459-efe14ef6055d",
    description: "Learn how to manage money, save smartly, and invest wisely.",
    stock: 46,
  },
  {
    id: 16,
    title: "Time Management Mastery",
    author: "Hannah Lewis",
    genre: "Self-Help",
    price: 289,
    rating: 4.3,
    pages: 220,
    language: "English",
    publishedYear: 2020,
    image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe",
    description:
      "Proven techniques to manage time effectively and reduce stress.",
    stock: 64,
  },
  {
    id: 17,
    title: "The Dark Path",
    author: "Noah Wilson",
    genre: "Fiction",
    price: 379,
    rating: 4.1,
    pages: 340,
    language: "English",
    publishedYear: 2023,
    image: "https://images.unsplash.com/photo-1496104679561-38b3b4d7f25e",
    description:
      "A thrilling novel filled with suspense and unexpected twists.",
    stock: 41,
  },
  {
    id: 18,
    title: "Node.js in Practice",
    author: "Samuel Young",
    genre: "Technology",
    price: 569,
    rating: 4.7,
    pages: 390,
    language: "English",
    publishedYear: 2022,
    image: "https://images.unsplash.com/photo-1517430816045-df4b7de11d1d",
    description: "Build fast and scalable backend applications using Node.js.",
    stock: 24,
  },
  {
    id: 19,
    title: "Build Your Confidence",
    author: "Megan Hall",
    genre: "Self-Help",
    price: 249,
    rating: 4.0,
    pages: 190,
    language: "English",
    publishedYear: 2018,
    image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93",
    description: "Simple steps to boost confidence and self-belief.",
    stock: 75,
  },
  {
    id: 20,
    title: "Modern Marketing Strategies",
    author: "Jason Reed",
    genre: "Business",
    price: 429,
    rating: 4.5,
    pages: 310,
    language: "English",
    publishedYear: 2021,
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66",
    description: "Learn modern marketing techniques used by top companies.",
    stock: 33,
  },
  {
    id: 21,
    title: "The Power of Habits",
    author: "Daniel Morris",
    genre: "Self-Help",
    price: 299,
    rating: 4.3,
    pages: 220,
    language: "English",
    publishedYear: 2019,
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    description: "Understand how habits shape your success and daily life.",
    stock: 60,
  },
  {
    id: 22,
    title: "Startup Success Guide",
    author: "Olivia Brown",
    genre: "Business",
    price: 399,
    rating: 4.2,
    pages: 280,
    language: "English",
    publishedYear: 2020,
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f",
    description: "A beginner-friendly guide to launching successful startups.",
    stock: 45,
  },
  {
    id: 23,
    title: "Mastering JavaScript",
    author: "Kevin White",
    genre: "Technology",
    price: 549,
    rating: 4.6,
    pages: 420,
    language: "English",
    publishedYear: 2022,
    image: "https://images.unsplash.com/photo-1517430816045-df4b7de01f17",
    description: "Advanced concepts and real-world JavaScript projects.",
    stock: 38,
  },
  {
    id: 24,
    title: "Healthy Mind, Healthy Life",
    author: "Sophia Green",
    genre: "Health",
    price: 279,
    rating: 4.1,
    pages: 200,
    language: "English",
    publishedYear: 2018,
    image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe",
    description: "Mental wellness tips for a balanced and peaceful life.",
    stock: 70,
  },
  {
    id: 25,
    title: "UI/UX Design Basics",
    author: "Aaron Smith",
    genre: "Design",
    price: 459,
    rating: 4.4,
    pages: 310,
    language: "English",
    publishedYear: 2021,
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
    description: "Learn the fundamentals of modern UI/UX design.",
    stock: 42,
  },
  {
    id: 26,
    title: "Financial Freedom",
    author: "Robert King",
    genre: "Finance",
    price: 349,
    rating: 4.0,
    pages: 260,
    language: "English",
    publishedYear: 2017,
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40",
    description:
      "Strategies to manage money and achieve financial independence.",
    stock: 55,
  },
  {
    id: 27,
    title: "Public Speaking Made Easy",
    author: "Emily Clark",
    genre: "Communication",
    price: 229,
    rating: 3.9,
    pages: 180,
    language: "English",
    publishedYear: 2016,
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d",
    description: "Overcome stage fear and improve public speaking skills.",
    stock: 65,
  },
  {
    id: 28,
    title: "Python for Beginners",
    author: "Michael Scott",
    genre: "Technology",
    price: 499,
    rating: 4.5,
    pages: 390,
    language: "English",
    publishedYear: 2023,
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475",
    description: "Step-by-step guide to learning Python programming.",
    stock: 50,
  },
  {
    id: 29,
    title: "Time Management Secrets",
    author: "Laura Wilson",
    genre: "Productivity",
    price: 259,
    rating: 4.2,
    pages: 210,
    language: "English",
    publishedYear: 2019,
    image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe",
    description: "Proven techniques to manage time efficiently.",
    stock: 58,
  },
  {
    id: 30,
    title: "Leadership Skills",
    author: "Andrew Parker",
    genre: "Management",
    price: 379,
    rating: 4.3,
    pages: 295,
    language: "English",
    publishedYear: 2020,
    image: "https://images.unsplash.com/photo-1515169067865-5387ec356754",
    description: "Develop leadership qualities for professional growth.",
    stock: 40,
  }
];
